export const rutaServicioBusquedaCanciones = "http://192.168.100.51:8091/artistas/buscar"
export const rutaServicioBusquedaPortadas = "http://192.168.100.51:8092/multimedia/buscarPortadaArtista/"
export const rutaServicioLogin = "http://localhost:8090/suscripcion/login"
export const rutaServicioRegistrar = "http://localhost:8090/suscripcion/RegistrarUsuario"
export const rutaServicioActualizarUsuario = "http://localhost:8090/suscripcion/actualizarUsuario"