
// export const rutaRegistrarArtista = "http://159.65.183.94:8091/artistas/crear"
// export const rutaActualizarArtista = "http://159.65.183.94:8091/artistas/actualizar"
// export const rutaServicioBuscarArtista = "http://159.65.183.94:8091/artistas/buscar"
// export const rutaRegistrarAlbum = "http://159.65.183.94:8091/albumes/crear"
// export const rutaActualizarAlbum = "http://159.65.183.94:8091/albumes/actualizar"
// export const rutaBuscarAlbum = "http://159.65.183.94:8091/albumes/buscar"
// export const rutaRegistrarCancion ="http://159.65.183.94:8091/canciones/crear"
// export const rutaActualizarCancion = "http://159.65.183.94:8091/canciones/actualizar"
// export const rutaBuscarCancion = "http://159.65.183.94:8091/canciones/buscar"
// export const rutaCrearListaDeReproduccion = "http://159.65.183.94:8091/ListaDeReproduccion/crear"
// export const rutaActualizarListaDeReproduccion = "http://159.65.183.94:8091/ListaDeReproduccion/actualizar"
// export const rutaAgregarCancionListaDeReproduccion = "http://159.65.183.94:8091/ListaDeReproduccion/agregarCancion"
// export const rutaElminarCancionListaDeReproduccion = "http://159.65.183.94:8091/ListaDeReproduccion/eliminarCancion"
// export const rutaBuscarListaDeReproduccion = "http://159.65.183.94:8091/ListaDeReproduccion/buscar"
// export const rutaObtenerCancionesListaDeReproduccion = "http://159.65.183.94:8091/ListaDeReproduccion/cancionesLista"

 //congiguracion el local

 export const rutaRegistrarArtista = "http://localhost:8091/artistas/crear"
export const rutaActualizarArtista = "http://localhost:8091/artistas/actualizar"
export const rutaServicioBuscarArtista = "http://localhost:8091/artistas/buscar"
export const rutaRegistrarAlbum = "http://localhost:8091/albumes/crear"
export const rutaActualizarAlbum = "http://localhost:8091/albumes/actualizar"
export const rutaBuscarAlbum = "http://localhost:8091/albumes/buscar"
export const rutaRegistrarCancion ="http://localhost:8091/canciones/crear"
export const rutaActualizarCancion = "http://localhost:8091/canciones/actualizar"
export const rutaBuscarCancion = "http://localhost:8091/canciones/buscar"
export const rutaCrearListaDeReproduccion = "http://localhost:8091/ListaDeReproduccion/crear"
export const rutaActualizarListaDeReproduccion = "http://localhost:8091/ListaDeReproduccion/actualizar"
export const rutaAgregarCancionListaDeReproduccion = "http://localhost:8091/ListaDeReproduccion/agregarCancion"
export const rutaElminarCancionListaDeReproduccion = "http://localhost:8091/ListaDeReproduccion/eliminarCancion"
export const rutaBuscarListaDeReproduccion = "http://localhost:8091/ListaDeReproduccion/buscar"
export const rutaObtenerCancionesListaDeReproduccion = "http://localhost:8091/ListaDeReproduccion/cancionesLista"
